version: '3.8'
services:
  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  django_gunicorn:
    build: .
    privileged: true
    volumes:
      - static:/app/static
    environment:
      - SECRET_KEY=<YOUR SECRET KEY>
      - RABBITMQ_HOST=rabbit
    ports:
      - "8000:8000"
    depends_on:
      - rabbit

  nginx:
    build: nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static: