# Generated by Django 4.1.5 on 2023-01-29 12:06

from django.db import migrations, models
import relays.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=relays.models.Relay.default_relay_name, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
    ]
