# Generated by Django 4.1.5 on 2023-01-31 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relays', '0002_relay_created_at_relay_updated_at_relaystatechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaystatechange',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relays.relay'),
        ),
        migrations.AlterField(
            model_name='relaystatechange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
