# Generated by Django 4.1.5 on 2023-03-18 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relays', '0004_remove_relay_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relay',
            name='description',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.CreateModel(
            name='RelayUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('field', models.CharField(max_length=50)),
                ('old_value', models.CharField(max_length=65535)),
                ('new_value', models.CharField(max_length=65535)),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relays.relay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelayCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relays.relay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
