# Generated by Django 4.1.5 on 2023-03-19 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relays', '0006_alter_relaycreationlog_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelayCreationLog',
            new_name='RelayCreateLog',
        ),
    ]
