# Generated by Django 4.1.5 on 2023-04-09 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relays', '0008_userrelaypermissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRelayPermissions',
            new_name='UserRelayPermission',
        ),
    ]
