# Generated by Django 4.1.5 on 2023-04-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0011_alter_userrelaypermission_permission_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelaypermission',
            name='permission_level',
            field=models.IntegerField(choices=[(0, 'Read Only'), (1, 'Control'), (2, 'Full Access')]),
        ),
    ]
