# Generated by Django 4.1.5 on 2023-04-10 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relays', '0012_alter_userrelaypermission_permission_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRelayPermission',
            new_name='UserRelayShare',
        ),
    ]
