# Generated by Django 4.1.5 on 2023-04-11 09:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relays', '0013_rename_userrelaypermission_userrelayshare'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrelayshare',
            unique_together={('user', 'relay')},
        ),
    ]
