# Generated by Django 4.1.5 on 2023-05-04 13:25

from django.db import migrations, models
import django.db.models.deletion
import relays.models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0015_rename_relaycreatelog_relaycreaterecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=relays.models.default_channel_name, max_length=100)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='relay',
            name='channel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='relays.channel'),
            preserve_default=False,
        ),
    ]
