# Generated by Django 4.1.5 on 2023-05-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0018_relay_synchronized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relay',
            name='synchronized',
        ),
    ]
